In [1]:
#
#  notebook to return the cell lengths
#

# Dependencies and Setup
import pandas as pd
import numpy as np
import requests
import time
import json

%matplotlib inline
import matplotlib.pyplot as plt

import os
import datetime

In [53]:
#import gun ownership csv file

gun_own_csv = "D:\Homework\PROJECT-2-Visualize-Me-Captain\data\gunownershipdataIV.csv"

gun_own_df = pd.read_csv(gun_own_csv, encoding="utf-8")
gun_own_df.head()

State State_ABV  gunOwnership      Pop
0         Alaska        AK         0.617   735720
1       Arkansas        AR         0.579  3026412
2          Idaho        ID         0.569  1790182
3  West Virginia        WV         0.542  1791951
4        Wyoming        WY         0.538   572381

In [54]:

# return the max length of characters in each column

measurer = np.vectorize(len)

res1 = measurer(gun_own_df.values.astype(str)).max(axis=0)
res1

array([14,  2, 20,  8])

In [52]:
gun_own_df.gunOwnership.astype("int64")

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
30    0
31    0
32    0
33    0
34    0
35    0
36    0
37    0
38    0
39    0
40    0
41    0
42    0
43    0
44    0
45    0
46    0
47    0
48    0
49    0
Name: gunOwnership, dtype: int64

In [47]:
gun_own_df.head()

State State_ABV  gunOwnership      Pop
0         Alaska        AK         0.617   735720
1       Arkansas        AR         0.579  3026412
2          Idaho        ID         0.569  1790182
3  West Virginia        WV         0.542  1791951
4        Wyoming        WY         0.538   572381

In [49]:
# Export file as a CSV, with the Pandas index and with the header....
gun_own_df.to_csv("D:\\Homework\\PROJECT-2-Visualize-Me-Captain\\data\\gun_own_data.csv", index=False, header=True)

In [4]:
#import mortality csv file

mortality_csv = "D:\Homework\PROJECT-2-Visualize-Me-Captain\data\mortality_data.csv"

mortality_df = pd.read_csv(mortality_csv, encoding="utf-8")
mortality_df.head()

index  year  month   intent  police sex   age                    race  \
0      1  2012      1  Suicide       0   M  34.0  Asian/Pacific Islander   
1      2  2012      1  Suicide       0   F  21.0                   White   
2      3  2012      1  Suicide       0   M  60.0                   White   
3      4  2012      2  Suicide       0   M  64.0                   White   
4      5  2012      2  Suicide       0   M  31.0                   White   

   hispanic            place     education  
0       100             Home           BA+  
1       100           Street  Some college  
2       100  Other specified           BA+  
3       100             Home           BA+  
4       100  Other specified        HS/GED

In [5]:

# return the max length of characters in each column

measurer = np.vectorize(len)

res1 = measurer(mortality_df.values.astype(str)).max(axis=0)
res1

array([ 6,  4,  2, 12,  1,  1,  5, 30,  3, 23, 12])

In [6]:
#import mother jones csv file

mother_jones_csv = "D:\Homework\PROJECT-2-Visualize-Me-Captain\data\Mother Jones - Mass Shootings Database, 1982 - 2019 - Sheet1.csv"

mother_jones_df = pd.read_csv(mother_jones_csv, encoding="utf-8")
mother_jones_df.head()

case            location       date  \
0      Dayton entertainment district shooting          Dayton, OH   8/4/2019   
1               El Paso Walmart mass shooting         El Paso, TX   8/3/2019   
2             Gilroy garlic festival shooting          Gilroy, CA  7/28/2019   
3  Virginia Beach municipal building shooting  Virginia Beach, VA  5/31/2019   
4          Harry Pratt Co. warehouse shooting          Aurora, IL  2/15/2019   

                                             summary  fatalities  injured  \
0  Connor Betts, 24, died during the attack, foll...           9       27   
1  Patrick Crusius, 21, who was apprehended by po...          22       26   
2  Santino William LeGan, 19, fired indiscriminat...           3       12   
3  DeWayne Craddock, 40, a municipal city worker ...          12        4   
4  Gary Martin, 45, went on a rampage inside the ...           5        6   

   total_victims location.1  age_of_shooter prior_signs_mental_health_issues  \
0             36      Other              24                                -   
1             48  Workplace              21                                -   
2             15      Other              19                              TBD   
3             16  Workplace              40                              TBD   
4             11  Workplace              45                              Yes   

   ... gender                                            sources  \
0  ...      M  https://www.nytimes.com/2019/08/04/us/dayton-o...   
1  ...      M  https://www.washingtonpost.com/nation/2019/08/...   
2  ...      M  https://www.cbsnews.com/live-news/garlic-festi...   
3  ...      M  https://www.washingtonpost.com/local/public-sa...   
4  ...      M  https://www.washingtonpost.com/nation/2019/02/...   

  mental_health_sources sources_additional_age   latitude   longitude  type  \
0                     -                      -  39.757312  -84.184947  Mass   
1                     -                      -  31.771068 -106.375655  Mass   
2                     -                      -  36.997191 -121.584819  Mass   
3                     -                      -  36.754420  -76.060378  Mass   
4                     -                      -  41.753725  -88.331057  Mass   

   year            City State  
0  2019          Dayton    OH  
1  2019         El Paso    TX  
2  2019          Gilroy    CA  
3  2019  Virginia Beach    VA  
4  2019          Aurora    IL  

[5 rows x 26 columns]

In [7]:
# list(mother_jones_df.columns.values)
# return the max length of characters in each column

measurer = np.vectorize(len)

res1 = measurer(mother_jones_df.values.astype(str)).max(axis=0)
res1

array([ 45,  36,  10, 908,   2,   3,   3,  10,   2,   8, 619, 131, 124,
       389, 328,  15,  13, 951, 444, 951,  18,  19,   5,   4,  24,   2])

In [31]:
#import registered weapons by state csv file

fbi_csv = "D:\\Homework\\PROJECT-2-Visualize-Me-Captain\\data\\fbi_data_2000-2017.csv"


fbi_df = pd.read_csv(fbi_csv, encoding="utf-8")
fbi_df.head()

index State  Offense_Year        Offense_Type  Offense_Count
0      0    AK          2000  aggravated_assault            985
1      1    AK          2000  all_other_offenses          14138
2      2    AK          2000               arson             24
3      3    AK          2000            burglary            583
4      4    AK          2000              curfew              6

In [32]:
fbi_df.count()

index            41472
State            41472
Offense_Year     41472
Offense_Type     41472
Offense_Count    41472
dtype: int64

In [33]:
fbi_df.Offense_Count.astype("int64")

0          985
1        14138
2           24
3          583
4            6
5          895
6         4517
7         1763
8         1043
9          257
10          20
11        1328
12           8
13         172
14         152
15          14
16         436
17          98
18          37
19           4
20          89
21         237
22           3
23           0
24           0
25           3
26           0
27           0
28        3588
29        1449
         ...  
41442     2418
41443       18
41444       49
41445      158
41446        0
41447        0
41448        0
41449        0
41450        1
41451        0
41452     1995
41453     1982
41454        0
41455      130
41456        9
41457      347
41458       48
41459        3
41460       43
41461        2
41462       43
41463       29
41464      107
41465     2004
41466       94
41467        6
41468       36
41469      493
41470       78
41471     2017
Name: Offense_Count, Length: 41472, dtype: int64

In [34]:
fbi_df.head()

index State  Offense_Year        Offense_Type  Offense_Count
0      0    AK          2000  aggravated_assault            985
1      1    AK          2000  all_other_offenses          14138
2      2    AK          2000               arson             24
3      3    AK          2000            burglary            583
4      4    AK          2000              curfew              6

In [37]:
# Export file as a CSV, with the Pandas index and with the header....
fbi_df.to_csv("D:\\Homework\\PROJECT-2-Visualize-Me-Captain\\data\\fbi_data_2000-2017.csv", index=True, header=True)

In [56]:
#import mortality csv file

reg_by_st_csv = "D:\Homework\PROJECT-2-Visualize-Me-Captain\data\registered_weapons_by_state.csv"

reg_by_st_df = pd.read_csv(reg_by_st_csv, encoding="utf-8")
reg_by_st_df.head()

FileNotFoundError: [Errno 2] File b'D:\\Homework\\PROJECT-2-Visualize-Me-Captain\\data\registered_weapons_by_state.csv' does not exist: b'D:\\Homework\\PROJECT-2-Visualize-Me-Captain\\data\registered_weapons_by_state.csv'

In [ ]:
# list(mother_jones_df.columns.values)
# return the max length of characters in each column

measurer = np.vectorize(len)

res1 = measurer(mother_jones_df.values.astype(str)).max(axis=0)
res1